### ISSUE TITLE
Bug in the code browser UI (wrong types displayed)

### ISSUE THREAD

**Issue by stof** [schmittjoh/php-code-analysis#1]
When entering a `if ($object instance FieldVote) {`, the object should be know as being a FieldVote instance inside the if.

Looking at the example on http://jmsyst.com/code-browser/#schmittjoh/JMSSecurityExtraBundle/master/Security/Acl/Voter/AclVoter.php, it does not seem to work in all cases. I took my FieldVote example from there.

Trying another place, I figured it is inferred properly a bit later line 67 so it seems weird. Either it is a displaying bug for the line 61 or the inference does not work in all cases.

**Comment by schmittjoh** [comment]
It's a bug in the UI, the underlying analysis is fine.

**Comment by schmittjoh** [comment]
I've added a new UI for the type displayment to the review details page. It's not as pretty as the previous one yet, but type information now reflects the exact same state that was used during analysis.
