### ISSUE TITLE
Github-linking seems broken

### ISSUE THREAD

**Issue by mxrth** [schmittjoh/php-code-analysis#10]
When trying to add a repository (logged in with email/password) I get a `security.authentication_error.general` displayed on the start-page. Login via github yields the same error.
Third party cookies are accepted, and authentication via github works on other pages such as travis-ci.

**Comment by pierredup** [comment]
+1

I also get the same error

**Comment by schmittjoh** [comment]
This should be fixed. 

Please comment again if you still experience problems here.
