### ISSUE TITLE
History of reviews for our repos

### ISSUE THREAD

**Issue by stof** [schmittjoh/php-code-analysis#14]
It would be great to have an history of reviews for our repos, to be able to access them again later (especially useful for builds triggered manually as they are not accessible through a PR page)

**Comment by schmittjoh** [comment]
You have a history (5 reviews atm) on the details page:
http://jmsyst.com/automated-code-reviews/repositories/FriendsOfSymfony/FOSUserBundle for example

**Comment by stof** [comment]
This page is fine for most cases IMO. But there is no link to it from the bundle list: http://jmsyst.com/automated-code-reviews/

**Comment by stof** [comment]
ah, sorry, the `Configure` button is sending to this page. But this is not obvious. It may need to be renamed (or a link should be added on the name in the left column)

**Comment by schmittjoh** [comment]
I've deployed a new version where the repository name is linked now.
