### ISSUE TITLE
[Feature] disabling the method name check for implementations of interfaces

### ISSUE THREAD

**Issue by stof** [schmittjoh/php-code-analysis#15]
If the method is part of an interface, the check on the method name should be disabled even if it returns a boolean as it cannot be renamed.
You can see an example in [StampieExtra](http://jmsyst.com/reviews/a47cb82a-4737-43f6-8274-6fb51f2a8566) where the `send` method of the mailer is part of an interface efined by another library and so cannot be renamed.

**Comment by schmittjoh** [comment]
I've disabled all naming checks on methods defined by contracts now (either interface, or abstract classes).

Will be in the next deployment.
