### ISSUE TITLE
Need more infos on fail

### ISSUE THREAD

**Issue by yohang** [schmittjoh/php-code-analysis#16]
I still fail to perform a full review on my project. 

Here is the log :

```
Package is being installed.
Package has been installed.
Dependencies are being installed.
Dependencies have been installed.
Scanning Package silex/silex (dev-master).
Scanning Package doctrine/common (dev-master).
Scanning Package symfony/console (dev-master).
Scanning Package yohang/calendr ().
Code is being reviewed now.
Oops, an internal error occurred.
Code is being reviewed now.
Oops, an internal error occurred.
Code is being reviewed now.
Oops, an internal error occurred.
Code is being reviewed now.
Oops, an internal error occurred.
```

Maybe it comes from my code, but the error gives me no informations.

Failing review : http://jmsyst.com/reviews/2f99613b-7799-428d-8542-470ae58523fb

**Comment by schmittjoh** [comment]
There was a trait related problems, but it passed now: 
http://jmsyst.com/reviews/a7260acb-f406-4742-b576-972be967b622

Traits are not fully supported yet, so you might see some false reports in that regard.
