### ISSUE TITLE
"Are you sure $ip has the correct type as * is not a sub-type of string"

### ISSUE THREAD

**Issue by lsmith77** [schmittjoh/php-code-analysis#19]
not sure where the \* comes from

http://jmsyst.com/reviews/21a05d77-bd53-4319-8244-50724d1d6025

**Comment by lsmith77** [comment]
ok i guess if i dont set a type via doc comments, not sure if it should complain.

**Comment by schmittjoh** [comment]
Probably not unless you are in strict mode otherwise it might get annoying.

**Comment by schmittjoh** [comment]
This is fixed.
