### ISSUE TITLE
Check doc comments of properties (@var)

### ISSUE THREAD

**Issue by asm89** [schmittjoh/php-code-analysis#2]
The bot didn't comment on the fact that `$saveOptions` should probably be `@var array` instead of string, while it does do this for the getter?

https://github.com/JMSBot/test-repository/pull/227/files#L1R44

**Comment by schmittjoh** [comment]
I see what you mean now, it does not check the doc comment of properties at this point.

**Comment by schmittjoh** [comment]
Could you re-open this on [scrutinizer-ci/php-analyzer](https://github.com/scrutinizer-ci/php-analyzer)?
