### ISSUE TITLE
Missing information on setting up GitHub hook

### ISSUE THREAD

**Issue by simensen** [schmittjoh/php-code-analysis#22]
I see that "Github Repository Hook" is not enabled for my repository. I am unable to find instructions on how to enable the hook. If the docs are there, perhaps they need to be made more prominent?

I assume that this hook needs to be in place to make the push push tracking work?

Great tool. Would love to give it a spin.

**Comment by stof** [comment]
you need to login with your github account on the jmsyst.com website, so that it can then setup the hook through the github API.

**Comment by simensen** [comment]
@stof Interesting. I had to log in before I could add my repository and I had logged in with my GitHub account. I just checked the site again and it now shows it as enabled. I guess there must have been some delay? Thanks.

**Comment by schmittjoh** [comment]
There is indeed a small delay, but I can see that it might be confusing; so, let's keep this open for now.

**Comment by schmittjoh** [comment]
This is now fixed, and will be in the next deployment. Thanks!
