### ISSUE TITLE
lots of false positives

### ISSUE THREAD

**Issue by lsmith77** [schmittjoh/php-code-analysis#24]
added comments to a few of them:
http://jmsyst.com/reviews/29329660-c3e6-4f43-b818-921f1154fe19

**Comment by schmittjoh** [comment]
I've fixed the regression now (see my comments inline on the review).

This caused a lot of false-positives to go away. I've not checked all messages, but those that I did looked legitimate:
http://jmsyst.com/reviews/263947ca-3e8a-48b5-857a-3bb33f930f31

**Comment by lsmith77** [comment]
what is the easiest way for me to redo the analysis from scratch?

**Comment by schmittjoh** [comment]
I've already run it for you (see the link above).

**Comment by lsmith77** [comment]
i think there are still issues:
http://jmsyst.com/reviews/263947ca-3e8a-48b5-857a-3bb33f930f31#comments-F1L146

**Comment by schmittjoh** [comment]
That one looks correct to me if you take a look at the method body of https://github.com/jackalope/jackalope/blob/master/src/Jackalope/NodeType/NodeTypeDefinition.php#L270; it can return null, no?

**Comment by lsmith77** [comment]
hmm .. you are right .. seems like we have to correct this.

**Comment by schmittjoh** [comment]
I guess I can close this. 

btw, you now can also report false-positives by click the icon on the top right of each comment.
