### ISSUE TITLE
Doesn't seem possible to "wakeup" a code review after previous travis fail

### ISSUE THREAD

**Issue by jonathaningram** [schmittjoh/php-code-analysis#25]
My repo didn't have travis enable, so it failed. I added a travis file and it now passes on travis, but I cannot find any way to trigger the code review to start again?

Here is the review: http://jmsyst.com/reviews/5443957d-b80d-43f8-be42-439e1b8242f2

**Comment by schmittjoh** [comment]
The review ran through fine actually, there was just nothing found :) 

The Travis CI status is just being displayed for convenience, and there is also integration with Travis to display code coverage inside the review for example.

If you like some comments however, you can change the default review config to enable a few more checks. See
http://jmsyst.com/automated-code-reviews/docs/config

**Comment by jonathaningram** [comment]
OK cool. Wonder if you could put an alert there saying something like "the review was successful but we did not find any comments. You can adjust your configuration by reading the doc" (something similar just to let the user know why there are no comments).
