### ISSUE TITLE
Broken autocomplete for the code-browser

### ISSUE THREAD

**Issue by stof** [schmittjoh/php-code-analysis#27]
Go on http://jmsyst.com/code-browser/ and enter `jackalope/jackalope` in the input. The ajax call goes to a weird url `https://api.github.com/legacy/repos/searchjackalope` (returning a 404 with a 200 status code because of being JSONP) and the console is filled with `b.repositories is undefined` errors

**Comment by schmittjoh** [comment]
I've fixed this particular bug. However, considering the new API limits of GitHub, you'll not have much fun with it :)

Eventually, I plan to incorporate the code-browser better on the review details page which should not only make it more accurate, but also easier to use for everybody.
