### ISSUE TITLE
composer.json load problem ?

### ISSUE THREAD

**Issue by teclliure** [schmittjoh/php-code-analysis#33]
When trying to build it says

"It seems like there was an unrecoverable error when analyzing your dependencies. This could be a problem with your composer.json, but might also be an internal error.

http://jmsyst.com/reviews/840ce12b-0a30-4c9e-ac63-0e6540e75877"

It should work ok because travis does the same with composer.json ... maybe an old composer version ?

**Comment by schmittjoh** [comment]
This is fixed now.

I've re-run it: http://jmsyst.com/reviews/8de97849-849e-4d38-9ffb-52d2cde69ea2
