### ISSUE TITLE
How can i fix "Dead Assignments Detection", when i define a variable and use it in other required file

### ISSUE THREAD

**Issue by twinh** [schmittjoh/php-code-analysis#34]
Hey!
My code looks like this, `$a` would be used in view file,how can i  avoid  `The assignment to $a seems to be dead.`

``` php
$a = 'foo';

require 'view.php';
```

**Comment by schmittjoh** [comment]
Thanks for the report.

This is not fixable on your end, I'll need to add it to the LiveVariableAnalysis. What you can do however is to delete the comment (top right corner), then it will automatically be hidden from future reviews.

**Comment by schmittjoh** [comment]
I've added support for `include`/`require` in the latest version (which will basically mark all variables as used at that point).

This will be in the next deployment.

**Comment by twinh** [comment]
:+1:  sounds excellent, and i think `get_defined_vars()` would also have the same effect with `include` / `require`

**Comment by schmittjoh** [comment]
I'm not so sure about `get_defined_vars` as this does not actually use the values of these variables. 

How do you use the return value of `get_defined_vars`? Inside dynamic variable access `${$var}`, or `compact` maybe?

**Comment by twinh** [comment]
I always use `get_defined_vars` in my controller

``` php
public function indexAction()
{
   $a = 'foo';

   $b = 'bar';

   // simply return all defined variables for view
   return get_defined_var();

   // rathar than
   return array(
     'a' => $a,
     'b' => $b,
     //...
   );
}
```

**Comment by schmittjoh** [comment]
I was under the impression that it only returned the defined names, but it indeed contains the values. So, I'll add that as well.

**Comment by twinh** [comment]
:)
