### ISSUE TITLE
Review hardly fails for an unknown reason

### ISSUE THREAD

**Issue by morgen2009** [schmittjoh/php-code-analysis#38]
The review process fails with an unknown internal error. See here
http://jmsyst.com/reviews/3458d38d-03a0-4bda-9b73-84bf387f121b

The previous review process without small changes in the annotation
https://github.com/morgen2009/JMSSerializerBundle/commit/32f447cb7bed59a57d2cc63f2a65ae7c3e84fe92 was fine.

**Comment by schmittjoh** [comment]
Thanks for reporting, I've made a pass over the error messages, they should be more insightful now.
