### ISSUE TITLE
Unrecoverable error when analyzing your dependencies

### ISSUE THREAD

**Issue by fabian** [schmittjoh/php-code-analysis#39]
Unfortunately the code review for my Symfony 2.1 project fails while scanning symfony/framework-standard-edition: http://jmsyst.com/reviews/5bc81d99-a05d-43c7-83f6-0256ba090743

I can't see any apparent reason - the Travis builds work fine.

**Comment by schmittjoh** [comment]
There was an inconsistent state in the class cache which led to problems.

Should be fixed now (I've run a review on your code which ran through fine).

**Comment by fabian** [comment]
Thanks, works fine again!
