### ISSUE TITLE
Wrong path handling in the code browser for substrings

### ISSUE THREAD

**Issue by stof** [schmittjoh/php-code-analysis#4]
If a folder name is a substring of a sibling folder, the longer name does not appear in the tree at the right place but as a child.

Example can be found on http://jmsyst.com/code-browser/#stof/StampieExtra/master/src/Stampie/Extra
The `EventListener` should appear here, but it appear as a child of the `Event` folder.

**Comment by schmittjoh** [comment]
I'm closing this as the code browser is replaced by the review details page.
