### ISSUE TITLE
Error when analysing Symfony

### ISSUE THREAD

**Issue by fabpot** [schmittjoh/php-code-analysis#44]
see http://jmsyst.com/reviews/09dba07d-4d1d-4994-a694-aef12a649273

**Comment by stof** [comment]
@fabpot For the class generated by the dumper tests (both for the routing and the DIC), you should exclude the paths where they are generated through the [`.jms.yml` file](http://jmsyst.com/automated-code-reviews/docs/config) to avoid multiple declarations

**Comment by schmittjoh** [comment]
Now, that the service is on the new website, I've had a look at this, and changed the config a bit. There are still a couple of false-positives, and in some places the type hints are not "precise" enough. I don't know how you would like to fix this (if at all). At any rate, we would need to go through the list and ignore/fix a couple of things:
https://scrutinizer-ci.com/g/symfony/symfony/inspections/7fd8d309-e692-4019-9903-7e538cf18076

For this reason, I've disabled the PHP Analyzer, and only enabled the PHP Code Sniffer with PSR1 and the PHP CS Fixer also on level PSR1. These two seemed uncontroversial.

You can change this config here:
https://scrutinizer-ci.com/g/symfony/symfony/settings/build-config
