### ISSUE TITLE
Unrecoverable error when analyzing dependencies

### ISSUE THREAD

**Issue by andrerom** [schmittjoh/php-code-analysis#45]
http://jmsyst.com/reviews/1daba672-d073-4abb-af48-7e2507638b06
& http://jmsyst.com/reviews/a1a5d58b-1a8a-49f4-a573-9e7ac0e14b3b

composer.json: https://github.com/ezsystems/ezp-next/blob/master/composer.json

**Comment by fajka** [comment]
I have probably similar problem:
http://jmsyst.com/reviews/2b8462ae-6a38-4145-b3d5-0b34038bda31

But...reviews never work for me, so I won't be surprised if my composer is invalid.
