### ISSUE TITLE
Missing type inference for is_resource

### ISSUE THREAD

**Issue by stof** [schmittjoh/php-code-analysis#48]
See the comment on https://scrutinizer-ci.com/g/symfony/symfony/inspections/7fd8d309-e692-4019-9903-7e538cf18076#comments-F2L170
As this line is inside a `is_resource($var)` check, it should know it is a resource

**Comment by schmittjoh** [comment]
Confirmed.

**Comment by schmittjoh** [comment]
Could you re-open this on [scrutinizer-ci/php-analyzer](https://github.com/scrutinizer-ci/php-analyzer) which now also contains the source code?

**Comment by stof** [comment]
done
