### ISSUE TITLE
Display whether package information is available in the UI

### ISSUE THREAD

**Issue by stof** [schmittjoh/php-code-analysis#6]
On http://jmsyst.com/code-browser/#friendsofsymfony/FOSUserBundle/master/Security/UserProvider.php line 63, the `$user` variable is shown as being `NoType` (where a space is missing btw). But this is wrong. First, the type inferred from the typehint is still valid, but the negated instanceof check throwing an exception could allow inferring it as `FOS\UserBundle\Model\User||FOS\UserBundle\Propel\User` (needed to accept the `getId` method call after that btw)

**Comment by schmittjoh** [comment]
This one is not as easy, but the current behavior is correct. The reasoning is that "FOSUserBundle" is not scanned, the system does not know how the DoctrineUser, and PropelUser relate to the SecurityUserInterface. That also means that DoctrineUser/PropelUser is not seen as a subtype of the SecurityUser. Therefore, it assumes that the if always evaluates to true, and finds no possible type for $user which would satisfy the `else` part of the if, hence the `NoType`. 

If the package were scanned, it would correctly infer $user to what you suggest. I added some tests for this. 

I will leave this open. It should probably something be added to the UI to tell that it did not have information about all classes.

**Comment by stof** [comment]
@schmittjoh shouldn't the bundle be scanned when the code review is activated ? Or will it be the case only next time a PR is opened in the bundle ?

And I find it weird to assume it evaluates to `true` (even if it is not a subtype, there is no reason to be always true). The type should at least keep using the typehint IMO.

**Comment by schmittjoh** [comment]
The first time a pull request is opened, the package is built, and then checked regularly for changes.

```
class A { }
class B { }

$a = new A();
if (!$a instanceof B) { // always true
    return;
}

// never reached
```

The good thing about assuming NoType is that it will allow to detect unreachable code because it should never be the case in "sane" code.

**Comment by schmittjoh** [comment]
I'm closing this as well as the UI on the review details page automatically has the package information from your `composer.json` file.
